Mobile and desktop
jovasal/complete-portfolio pull request #1
Opened 2023-06-09 18:26 UTC by jovasal

changes between mobile and desktop

2023-06-11 03:14 UTC, Tufahel requested changes
Hi @jovasal, 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, where a professional README is not implemented.

Kindly implement the [professional README](https://github.com/microverseinc/readme-template) introduced by microverse. The only optional segment is `FAQ` of that [README](https://github.com/microverseinc/readme-template). You need to add every other option and customize it as per your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-11 05:29 UTC, topeogunleye commented
Hi @jovasal, I need you to share the link to your first repository and the pull request that was reviewed on. I may have to start from scratch and check everything in your code.

2023-06-11 06:05 UTC, jovasal commented
hi @topeogunleye Thank you so much for your answer.

I can explain you.

First of all, I made a mistake and I sent a before activity under my fault. A first code review never rejected this project and I need to use that last repository for this activity:

https://github.com/jovasal/Complete-Mobile-Figma-Portfolio/pull/1

![image](https://github.com/jovasal/complete-portfolio/assets/35693330/384da57c-faa3-4f11-b6b8-94e390cc73f9)

I made another activity in that repository, but code review saw that and continued choking that:
![image](https://github.com/jovasal/complete-portfolio/assets/35693330/bebcf4ea-23f9-425a-8d8b-cd7073593ba3)
![image](https://github.com/jovasal/complete-portfolio/assets/35693330/5bd8e1eb-8394-438f-918a-1f4833381412)


Then, I sent an update for this activity and another coder review told me that can't proceed and commented that I need to open a new pull request. So I continue in my original repository for this activity.

![image](https://github.com/jovasal/complete-portfolio/assets/35693330/9719f8f4-4d66-43f2-9aa9-9e678fec54d7)

Thank you so much and I really appreciate your time

2023-06-11 06:13 UTC, topeogunleye requested changes
Hi @jovasal, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Followed Github flow :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Please check review comments below.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-11 06:13 UTC, topeogunleye commented on style.css
> +@media only screen and (max-width: 768px) {
- You have used max-width for your media queries, which means that your styles will apply to screens that are smaller than the specified width. This is fine for mobile breakpoints, but for desktop breakpoints, you should use min-width instead. This way, your styles will apply to screens that are larger than the specified width. For example, you can use:

@media only screen and (min-width: 768px) {
  /* your desktop styles here */
}

This will make your code more responsive and easier to maintain.

2023-06-11 06:13 UTC, topeogunleye commented on index.html
> +      <div class="container-cards">
I kindly suggest you please follow the Figma design closely in terms of spacing, margins, etc.

- [ ] Kindly ensure that your html, css , js tags are spaced like they are spaced in the Figma design.
- [ ] Kindly ensure that the company "Facebook" has a font weight of 500 as seen from the Figma design.


| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="713" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/aa542e7d-8707-4add-a7cc-4baff63acc6d"> | <img width="549" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/8ebb409a-1ff0-421a-a515-5bc74574f8e1">  |

2023-06-11 06:13 UTC, topeogunleye commented on style.css
> +.go-buttontonic {
- [ ] I kindly suggest that you add the correct button interaction for enable (default state) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the enabled state has the `color: #6070FF;` not `color: #396df2`

### EXAMPLE:
**for enable(default button) state**
```
button {
   color: #6070FF;
}
```

2023-06-11 06:13 UTC, topeogunleye commented on style.css
> +.go-buttontonic:hover {
- [ ] I kindly suggest that you add the correct button interactions for hover as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on hover has the `background-color: #6070FF;`

### EXAMPLE:
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2023-06-11 06:13 UTC, topeogunleye commented on style.css
> +.go-buttontonic {
- [ ] I kindly suggest that you add the button interactions for active (when it's pressed) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on hover has the  `background-color: #2230D2;` 
### EXAMPLE:
```
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```

2023-06-11 06:13 UTC, topeogunleye commented on index.html
> +        <div class="card1">
- [ ] I kindly suggest that you follow the Figma design closely in designing your about me section.
- [ ] Please kindly ensure that you space your social icons correctly.
- [ ] Please kindly ensure that you space your languages section correctly.
- [ ] Please kindly ensure that the about me takes 40%, while the professional skills on the other side takes 60% of the page width.
- [ ] Please kindly space your Javascript, HTML and CSS tags correctly as seen on the Figma design.

|   |  |
| ------------- | ------------- |
| Your Design  | <img width="898" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/a635207f-ade7-40eb-8756-577190fb8adf">  |
| Figma Design  | 
<img width="548" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/49ec7195-c235-43e9-a86a-4001b5c08399">  |

2023-06-11 06:13 UTC, topeogunleye commented on index.html
> +      <section id="consection">
- [ ] I kindly suggest that you follow the Figma design closely in designing your contact section:

- Kindly ensure that your inputs are the same width like they are on the figma design
- Kindly ensure that the padding of the inputs(space within) is the same as the Figma design.


|   |  |
| ------------- | ------------- |
| Your Design  | <img width="695" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/fcba8c81-65b0-4738-89a9-887d933d6c0a">  |
| Figma design | <img width="540" alt="image" src="https://github.com/jovasal/complete-portfolio/assets/52934128/689e2c6f-fda0-4108-9ddf-664edc4d39a0">  |

2023-06-11 06:13 UTC, topeogunleye commented on README.md
> +Clone this repository to your desired folder:
Kindly add commands to close the repo E.G
```
cd my-folder
  git clone git@github.com:myaccount/my-project.git
```

2023-06-11 06:13 UTC, topeogunleye commented on README.md
> +
- [OPTIONAL]

- [ ] I kindly suggest that you add a getting started to show how your project is run locally

## EXAMPLE

```
## Getting Started
To get a local copy up and running, follow the steps in Setup below.

### Prerequisites
Basic knowledge of HTML, CSS, and JavaScript.

### Setup
If you installed git you can clone the code to your machine, or download a ZIP of all the files directly.

[Download the ZIP from this location](https://github.com/danielsafari143/portfolio/archive/refs/heads/master.zip), or run the following [git](https://git-scm.com/downloads) command to clone the files to your machine:
```

```bash
git clone https://github.com/danielsafari143/portfolio.git
```

```
- Once the files are on your machine, open the _portfolio_ folder in [Visual Studio Code](https://code.visualstudio.com/)

- With the files open in Visual Studio Code, press the **Go Live** button at the bottom of the window to launch the files with [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

### Install

The following tools help make easier to work with sample code.

- [git](https://git-scm.com/downloads): A tool for managing source code
- [Visual Studio Code](https://code.visualstudio.com/): A source code editor
- [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer): A simple web server utility for Visual Studio Code
```
The above is an example and may need to be adapted to your project

2023-06-11 06:18 UTC, topeogunleye commented
> hi @topeogunleye Thank you so much for your answer.
> 
> I can explain you.
> 
> First of all, I made a mistake and I sent a before activity under my fault. A first code review never rejected this project and I need to use that last repository for this activity:
> 
> [jovasal/Complete-Mobile-Figma-Portfolio#1](https://github.com/jovasal/Complete-Mobile-Figma-Portfolio/pull/1)
> 
> ![image](https://user-images.githubusercontent.com/35693330/244916607-384da57c-faa3-4f11-b6b8-94e390cc73f9.png)
> 
> I made another activity in that repository, but code review saw that and continued choking that: ![image](https://user-images.githubusercontent.com/35693330/244916691-bebcf4ea-23f9-425a-8d8b-cd7073593ba3.png) ![image](https://user-images.githubusercontent.com/35693330/244916702-5bd8e1eb-8394-438f-918a-1f4833381412.png)
> 
> Then, I sent an update for this activity and another coder review told me that can't proceed and commented that I need to open a new pull request. So I continue in my original repository for this activity.
> 
> ![image](https://user-images.githubusercontent.com/35693330/244916544-9719f8f4-4d66-43f2-9aa9-9e678fec54d7.png)
> 
> Thank you so much and I really appreciate your time

@jovasal, Thanks for explaining. please for future pull requests. Always include a link to the previous pull request in the pr description so that the new reviewer can have a place to start from and not start reviewing all over from the beginning.

2023-06-13 00:16 UTC, closed without merging

2023-06-13 00:16 UTC, jovasal commented
restart again